// Write a JavaScript program to generate a random number and store it in a variable.
// The program then takes an input from the user and checks whether the entered number is less,equal or greater than the random number generated by the system.
// 100 - (no of guesses) is the score of the user. The program is expected to terminate once the number is guessed. Number should be in between 1-100

// Code -->
let key = 'y'
let random = Math.floor(Math.random()*100);
let guess = 0
while (key=='y')
{
    console.log("Now guess a number")
    let num = prompt("Enter your number =")
    if (num>random){
        console.log("Your choice is too high!! ")
        guess++
    }
    else if(num<random){
        console.log("Your choice is too low")
        guess++
    }
    else{
        console.log("Correct! You guessed the number right.")
        key = "N"
    }
}
console.log(`Your score is ${100-guess}`)